// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
*/
var Specification = Specification || {};

/**
 * @constructor
 */
Specification.Product = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Product}
 */
Specification.Product.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Product=} obj
 * @returns {Specification.Product}
 */
Specification.Product.getRootAsProduct = function(bb, obj) {
  return (obj || new Specification.Product).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Product.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.EffectiveStartDate = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.AvailableStartDate = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.EffectiveEndDate = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.AvailableEndDate = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.ElementGuid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.ElementTypeGuid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.BusinessID = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.Name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.Description = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.CategoryID = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.MaxCustPortfolioInstances = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product.prototype.MinCustPortfolioInstances = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {Specification.MappingRules=} obj
 * @returns {Specification.MappingRules}
 */
Specification.Product.prototype.MappingRules = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 30);
  return offset ? (obj || new Specification.MappingRules).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Specification.Product.prototype.MappingRulesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 30);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {Specification.Product_To_Product=} obj
 * @returns {Specification.Product_To_Product}
 */
Specification.Product.prototype.ProductToProduct = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 32);
  return offset ? (obj || new Specification.Product_To_Product).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Specification.Product.prototype.ProductToProductLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 32);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Product.startProduct = function(builder) {
  builder.startObject(15);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.Product.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} EffectiveStartDateOffset
 */
Specification.Product.addEffectiveStartDate = function(builder, EffectiveStartDateOffset) {
  builder.addFieldOffset(1, EffectiveStartDateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} AvailableStartDateOffset
 */
Specification.Product.addAvailableStartDate = function(builder, AvailableStartDateOffset) {
  builder.addFieldOffset(2, AvailableStartDateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} EffectiveEndDateOffset
 */
Specification.Product.addEffectiveEndDate = function(builder, EffectiveEndDateOffset) {
  builder.addFieldOffset(3, EffectiveEndDateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} AvailableEndDateOffset
 */
Specification.Product.addAvailableEndDate = function(builder, AvailableEndDateOffset) {
  builder.addFieldOffset(4, AvailableEndDateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ElementGuidOffset
 */
Specification.Product.addElementGuid = function(builder, ElementGuidOffset) {
  builder.addFieldOffset(5, ElementGuidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ElementTypeGuidOffset
 */
Specification.Product.addElementTypeGuid = function(builder, ElementTypeGuidOffset) {
  builder.addFieldOffset(6, ElementTypeGuidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} BusinessIDOffset
 */
Specification.Product.addBusinessID = function(builder, BusinessIDOffset) {
  builder.addFieldOffset(7, BusinessIDOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} NameOffset
 */
Specification.Product.addName = function(builder, NameOffset) {
  builder.addFieldOffset(8, NameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} DescriptionOffset
 */
Specification.Product.addDescription = function(builder, DescriptionOffset) {
  builder.addFieldOffset(9, DescriptionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} CategoryIDOffset
 */
Specification.Product.addCategoryID = function(builder, CategoryIDOffset) {
  builder.addFieldOffset(10, CategoryIDOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MaxCustPortfolioInstancesOffset
 */
Specification.Product.addMaxCustPortfolioInstances = function(builder, MaxCustPortfolioInstancesOffset) {
  builder.addFieldOffset(11, MaxCustPortfolioInstancesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MinCustPortfolioInstancesOffset
 */
Specification.Product.addMinCustPortfolioInstances = function(builder, MinCustPortfolioInstancesOffset) {
  builder.addFieldOffset(12, MinCustPortfolioInstancesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MappingRulesOffset
 */
Specification.Product.addMappingRules = function(builder, MappingRulesOffset) {
  builder.addFieldOffset(13, MappingRulesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Specification.Product.createMappingRulesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Specification.Product.startMappingRulesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ProductToProductOffset
 */
Specification.Product.addProductToProduct = function(builder, ProductToProductOffset) {
  builder.addFieldOffset(14, ProductToProductOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Specification.Product.createProductToProductVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Specification.Product.startProductToProductVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Product.endProduct = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Specification.Product.finishProductBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
Specification.Meta = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Meta}
 */
Specification.Meta.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Meta.getRootAsMeta = function(bb, obj) {
  return (obj || new Specification.Meta).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Meta.prototype.ID = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Meta.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
Specification.Meta.prototype.isTechnical = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Meta.prototype.path = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Meta.prototype.OmniformName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Meta.prototype.BusinessID = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Meta.startMeta = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} IDOffset
 */
Specification.Meta.addID = function(builder, IDOffset) {
  builder.addFieldOffset(0, IDOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
Specification.Meta.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isTechnical
 */
Specification.Meta.addIsTechnical = function(builder, isTechnical) {
  builder.addFieldInt8(2, +isTechnical, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pathOffset
 */
Specification.Meta.addPath = function(builder, pathOffset) {
  builder.addFieldOffset(3, pathOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} OmniformNameOffset
 */
Specification.Meta.addOmniformName = function(builder, OmniformNameOffset) {
  builder.addFieldOffset(4, OmniformNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} BusinessIDOffset
 */
Specification.Meta.addBusinessID = function(builder, BusinessIDOffset) {
  builder.addFieldOffset(5, BusinessIDOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Meta.endMeta = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.Product_To_Product = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Product_To_Product}
 */
Specification.Product_To_Product.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Product_To_Product=} obj
 * @returns {Specification.Product_To_Product}
 */
Specification.Product_To_Product.getRootAsProduct_To_Product = function(bb, obj) {
  return (obj || new Specification.Product_To_Product).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Product_To_Product.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product_To_Product.prototype.AssociationStartDate = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product_To_Product.prototype.AssociationEndDate = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product_To_Product.prototype.MaxOccurs = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product_To_Product.prototype.MinOccurs = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Product_To_Product.prototype.DefaultCardinality = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {Specification.Product=} obj
 * @returns {Specification.Product}
 */
Specification.Product_To_Product.prototype.Product = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? (obj || new Specification.Product).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Product_To_Product.startProduct_To_Product = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.Product_To_Product.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} AssociationStartDateOffset
 */
Specification.Product_To_Product.addAssociationStartDate = function(builder, AssociationStartDateOffset) {
  builder.addFieldOffset(1, AssociationStartDateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} AssociationEndDateOffset
 */
Specification.Product_To_Product.addAssociationEndDate = function(builder, AssociationEndDateOffset) {
  builder.addFieldOffset(2, AssociationEndDateOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MaxOccursOffset
 */
Specification.Product_To_Product.addMaxOccurs = function(builder, MaxOccursOffset) {
  builder.addFieldOffset(3, MaxOccursOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MinOccursOffset
 */
Specification.Product_To_Product.addMinOccurs = function(builder, MinOccursOffset) {
  builder.addFieldOffset(4, MinOccursOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} DefaultCardinalityOffset
 */
Specification.Product_To_Product.addDefaultCardinality = function(builder, DefaultCardinalityOffset) {
  builder.addFieldOffset(5, DefaultCardinalityOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ProductOffset
 */
Specification.Product_To_Product.addProduct = function(builder, ProductOffset) {
  builder.addFieldOffset(6, ProductOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Product_To_Product.endProduct_To_Product = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.Exists = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Exists}
 */
Specification.Exists.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Exists=} obj
 * @returns {Specification.Exists}
 */
Specification.Exists.getRootAsExists = function(bb, obj) {
  return (obj || new Specification.Exists).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Exists.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Exists.prototype.Entity = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Exists.startExists = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.Exists.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} EntityOffset
 */
Specification.Exists.addEntity = function(builder, EntityOffset) {
  builder.addFieldOffset(1, EntityOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Exists.endExists = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.Scope = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Scope}
 */
Specification.Scope.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Scope=} obj
 * @returns {Specification.Scope}
 */
Specification.Scope.getRootAsScope = function(bb, obj) {
  return (obj || new Specification.Scope).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Scope.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Scope.prototype.Name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Scope.prototype.Description = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Scope.prototype.Seq = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Scope.startScope = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.Scope.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} NameOffset
 */
Specification.Scope.addName = function(builder, NameOffset) {
  builder.addFieldOffset(1, NameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} DescriptionOffset
 */
Specification.Scope.addDescription = function(builder, DescriptionOffset) {
  builder.addFieldOffset(2, DescriptionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} SeqOffset
 */
Specification.Scope.addSeq = function(builder, SeqOffset) {
  builder.addFieldOffset(3, SeqOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Scope.endScope = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.Conditions = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Conditions}
 */
Specification.Conditions.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Conditions=} obj
 * @returns {Specification.Conditions}
 */
Specification.Conditions.getRootAsConditions = function(bb, obj) {
  return (obj || new Specification.Conditions).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Conditions.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Conditions.prototype.Name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {Specification.Exists=} obj
 * @returns {Specification.Exists}
 */
Specification.Conditions.prototype.Exists = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new Specification.Exists).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Specification.Conditions.prototype.ExistsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {Specification.Scope=} obj
 * @returns {Specification.Scope}
 */
Specification.Conditions.prototype.Scope = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new Specification.Scope).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Conditions.startConditions = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.Conditions.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} NameOffset
 */
Specification.Conditions.addName = function(builder, NameOffset) {
  builder.addFieldOffset(1, NameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ExistsOffset
 */
Specification.Conditions.addExists = function(builder, ExistsOffset) {
  builder.addFieldOffset(2, ExistsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Specification.Conditions.createExistsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Specification.Conditions.startExistsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ScopeOffset
 */
Specification.Conditions.addScope = function(builder, ScopeOffset) {
  builder.addFieldOffset(3, ScopeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Conditions.endConditions = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.TriggerEvents = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.TriggerEvents}
 */
Specification.TriggerEvents.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.TriggerEvents=} obj
 * @returns {Specification.TriggerEvents}
 */
Specification.TriggerEvents.getRootAsTriggerEvents = function(bb, obj) {
  return (obj || new Specification.TriggerEvents).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.TriggerEvents.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.TriggerEvents.prototype.Name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.TriggerEvents.startTriggerEvents = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.TriggerEvents.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} NameOffset
 */
Specification.TriggerEvents.addName = function(builder, NameOffset) {
  builder.addFieldOffset(1, NameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.TriggerEvents.endTriggerEvents = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.Actions = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.Actions}
 */
Specification.Actions.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.Actions=} obj
 * @returns {Specification.Actions}
 */
Specification.Actions.getRootAsActions = function(bb, obj) {
  return (obj || new Specification.Actions).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.Actions.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Actions.prototype.Name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Actions.prototype.Sequence = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.Actions.prototype.Target = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.Actions.startActions = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.Actions.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} NameOffset
 */
Specification.Actions.addName = function(builder, NameOffset) {
  builder.addFieldOffset(1, NameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} SequenceOffset
 */
Specification.Actions.addSequence = function(builder, SequenceOffset) {
  builder.addFieldOffset(2, SequenceOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} TargetOffset
 */
Specification.Actions.addTarget = function(builder, TargetOffset) {
  builder.addFieldOffset(3, TargetOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.Actions.endActions = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Specification.MappingRules = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Specification.MappingRules}
 */
Specification.MappingRules.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Specification.MappingRules=} obj
 * @returns {Specification.MappingRules}
 */
Specification.MappingRules.getRootAsMappingRules = function(bb, obj) {
  return (obj || new Specification.MappingRules).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {Specification.Meta=} obj
 * @returns {Specification.Meta}
 */
Specification.MappingRules.prototype.Meta = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Specification.Meta).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.MappingRules.prototype.Name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Specification.MappingRules.prototype.Sequence = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {Specification.Conditions=} obj
 * @returns {Specification.Conditions}
 */
Specification.MappingRules.prototype.Conditions = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new Specification.Conditions).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {Specification.TriggerEvents=} obj
 * @returns {Specification.TriggerEvents}
 */
Specification.MappingRules.prototype.TriggerEvents = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new Specification.TriggerEvents).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {Specification.Actions=} obj
 * @returns {Specification.Actions}
 */
Specification.MappingRules.prototype.Actions = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new Specification.Actions).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Specification.MappingRules.startMappingRules = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MetaOffset
 */
Specification.MappingRules.add_meta = function(builder, MetaOffset) {
  builder.addFieldOffset(0, MetaOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} NameOffset
 */
Specification.MappingRules.addName = function(builder, NameOffset) {
  builder.addFieldOffset(1, NameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} SequenceOffset
 */
Specification.MappingRules.addSequence = function(builder, SequenceOffset) {
  builder.addFieldOffset(2, SequenceOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ConditionsOffset
 */
Specification.MappingRules.addConditions = function(builder, ConditionsOffset) {
  builder.addFieldOffset(3, ConditionsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} TriggerEventsOffset
 */
Specification.MappingRules.addTriggerEvents = function(builder, TriggerEventsOffset) {
  builder.addFieldOffset(4, TriggerEventsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ActionsOffset
 */
Specification.MappingRules.addActions = function(builder, ActionsOffset) {
  builder.addFieldOffset(5, ActionsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Specification.MappingRules.endMappingRules = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.Specification = Specification;
